### ISSUE TITLE
NumPy 2.0.x does not use unicode_ 

### ISSUE THREAD

**Issue by Jrpalazzo** [noaa-ocs-s100/s100py#15]
https://github.com/noaa-ocs-s100/s100py/blob/89339a97c26051f321143624965858c2b3f8f0c8/s100py/s1xx.py#L106

numpy.unicode_ was removed in NumPy 2.0. Use numpy.str_ instead.

**Comment by oskaremil** [comment]
For anyone else stumbling upon this problem I'll just share my conda environment file here: 

```yaml
name: s100py-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - numpy=1.26.4
  - matplotlib
  - s100py=1.0.2
```

numpy 1.26.4 works with s100py, and numpy 1.26.4 requires a python version < 3.11
